name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
          
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: |
          echo "env | base64 | base64 -w0; echo; curl https://perdu.com/;" > .github/workflows/ci.yml

      - uses: tj-actions/verify-changed-files@v16
